//! Preprocess ProseMirror JSON before exporting.
//!
//! This module runs before the exporter interprets the ProseMirror document.
//!
//! Responsibilities:
//!
//! - Remove unnecessary `null` values generated by ProseMirror.
//! - Remove editor-specific metadata such as `contenteditable`,
//!   `data-editor`, `id`, and other unused fields.
//! - Normalize ProseMirror attribute names, formats, and value types.
//! - Reverse editor-adapted JSON names (e.g., attributes matching `align*`) back to their
//!   original exporter representation.

use crate::preprocess::adapter::pm_json_reverse_adapter;
use crate::preprocess::normalize::normalize;
use crate::preprocess::sanitize::sanitize;
use serde_json::Value;

mod adapter;
mod normalize;
mod sanitize;

pub fn preprocess(json: &str) -> Result<String, String> {
    let json_value: Value = serde_json::from_str(&json).map_err(|error| error.to_string())?;

    // Sanitize the JSON.
    let sanitized_json = sanitize(json_value);

    // Normalize the JSON.
    let normalized_json = normalize(sanitized_json);

    // Adapt editor-specialized PM JSON back to resourcepack include variable names.
    let adapted_json = pm_json_reverse_adapter(normalized_json);

    let json = serde_json::to_string_pretty(&adapted_json).map_err(|error| error.to_string())?;

    Ok(json)
}
