version: 2
updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@tiptap/*"
      - dependency-name: "typescript"
      - dependency-name: "vite"
      - dependency-name: "eslint"
      - dependency-name: "esbuild"
      - dependency-name: "prettier"
      - dependency-name: "@vitejs/plugin-vue"

  # Code View subproject
  - package-ecosystem: "npm"
    directory: "/public/code_view"
    schedule:
      interval: "weekly"

  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "time"
      - dependency-name: "rusqlite"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
