name: Build Windows Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          maturin build --release --manifest-path Cargo.toml
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Rust module
        working-directory: engine/rust_engine/ftml_py
        run: maturin build --release

      - name: Install Rust wheel
        working-directory: engine/rust_engine/ftml_py
        run: pip install target/wheels/*.whl

      - name: Build EXE
        run: |
          pyinstaller Main.py --noconsole `
          --hidden-import ftml_parser `
          --hidden-import ftml_py
          --add-data "engine;engine" `
          --add-data "ui;ui" `
          --add-data "utils;utils" `
          --add-data "controllers;controllers" `
          --add-data "formats;formats"

      - name: Zip build
        run: |
          Compress-Archive -Path dist/Main/* -DestinationPath scp-editor-windows.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: scp-editor-windows.zip
